### ISSUE TITLE
Include geckodriver.exe in the project folder and make hardcoded path to relative path

### ISSUE THREAD

**Issue by abhishekbits** [jinsonbits/GUIAutomationUsingSeleniumPython#3]
self.driver=webdriver.Firefox(executable_path="D:\MTECH-BITS-PILANI\seleniumautomation\drivers\geckodriver-v0.29.0-win64\geckodriver.exe")
This path is hardcoded,so it does not work on any other system than the author's system.

geckodriver.exe --> Add this file to the project.
add a new folder named 'drivers' and include the necessary driver servers in the folder.

**Comment by jinsonbits** [comment]
geckodriver for firefox is added with the previous commit. Proceed to close the issue.
